### ISSUE TITLE
`prbt_hardware_support` does not install any lib

### ISSUE THREAD

**Issue by hsd-dev** [PilzDE/pilz_robots#105]
I am working on Ubuntu 16.04 with ROS kinetic and ROS2 crystal. While building `ros1_bridge`, I get an error:

```
--- stderr: ros1_bridge                         
CMake Error at cmake/find_ros1_package.cmake:75 (message):
  pkg-config module 'prbt_hardware_support' failed to find library
  'prbt_hardware_support'
Call Stack (most recent call first):
  CMakeLists.txt:50 (find_ros1_package)
```
Similar to the issue [here](https://github.com/ros2/ros1_bridge/issues/88), `prbt_hardware_support` exports the package as a library, but does not install any libs. By commenting out the [line](https://github.com/PilzDE/pilz_robots/blob/kinetic-devel/prbt_hardware_support/CMakeLists.txt#L36), I am able to build `ros1_bridge`

**Comment by jschleicher** [comment]
Yep, thanks for reporting. Actually the package does not build any lib, so the line isn't necessary.
