### ISSUE TITLE
Pilz_tutorial_4 with real robot

### ISSUE THREAD

**Issue by OndrejNedelka** [PilzDE/pilz_robots#118]
### Commit
At which commit was the issue/bug observed?

### Steps to reproduce
How can the issue/bug be reproduced?
`roslaunch pilz_tutorial my_application.launch`

### Expected behavior
Physical robot should move as in RVIZ.

### Observed behavior
Launch fails at error:
`unused args [rviz_config] for include of [/opt/ros/kinetic/share/prbt_moveit_config/launch/moveit_rviz.launch]
The traceback for the exception was written to the log file`

My package:
(Tutorial nr. 4 with modified launch file)
[pilz_tutorial_4.tar.gz](https://github.com/PilzDE/pilz_robots/files/3148522/pilz_tutorial_4.tar.gz)

Version of used packages
`Požadované=Neznámé/Instalovat/Odinstalovat/Vyčistit/Podržet
| Stav=Ne/Instalován/Konfigurační soubory/Rozbalen/Nezkonfigurován/Nekompletní
| instalace/Očekávané spouštěče/Nevyřízené spouštěče
|/ Chyba?=(nic)/Nutná přeinstalace (Stav,Chyba: velké písmeno=chyba)
||/ Název                                        Verze                              Architektura Popis
+++-============================================-==================================-============-======================================================================================================================
ii  ros-kinetic-pilz-control                     0.4.7-0xenial-20190320-154545-0800 amd64        This package provides a specialized joint_trajectory_controller that can be moved into holding state via service call.
ii  ros-kinetic-pilz-extensions                  0.3.6-0xenial-20190320-214603-0800 amd64        The pilz_extensions package.
ii  ros-kinetic-pilz-industrial-motion           0.3.6-0xenial-20190401-170338-0800 amd64        The pilz_industrial_motion package
ii  ros-kinetic-pilz-industrial-motion-testutils 0.3.6-0xenial-20190320-220715-0800 amd64        Helper scripts and functionality to test industrial motion generation
ii  ros-kinetic-pilz-msgs                        0.3.6-0xenial-20190320-215552-0800 amd64        The pilz_msgs package
ii  ros-kinetic-pilz-robot-programming           0.3.6-0xenial-20190401-165342-0800 amd64        An Easy to use API to execute standard industrial robot commands like Ptp, Lin, Circ and Sequence using Moveit.
ii  ros-kinetic-pilz-robots                      0.4.7-0xenial-20190320-235204-0800 amd64        The metapackage
ii  ros-kinetic-pilz-testutils                   0.4.7-0xenial-20190320-130907-0800 amd64        This package contains testing utilities used by Pilz packages.
ii  ros-kinetic-pilz-trajectory-generation       0.3.6-0xenial-20190401-163544-0800 amd64        The pilz_trajectory_generation package containing the MoveIt! plugin pilz_command_planner.
`

`Požadované=Neznámé/Instalovat/Odinstalovat/Vyčistit/Podržet
| Stav=Ne/Instalován/Konfigurační soubory/Rozbalen/Nezkonfigurován/Nekompletní
| instalace/Očekávané spouštěče/Nevyřízené spouštěče
|/ Chyba?=(nic)/Nutná přeinstalace (Stav,Chyba: velké písmeno=chyba)
||/ Název                                      Verze                              Architektura Popis
+++-==========================================-==================================-============-============================================================================================================================================
ii  ros-kinetic-prbt-gazebo                    0.4.7-0xenial-20190320-230328-0800 amd64        Launch prbt robot in an empty Gazebo world.
ii  ros-kinetic-prbt-grippers                  0.0.2-0xenial-20190401-162607-0800 amd64        The package provides gripper support for the pilz_robots package.
ii  ros-kinetic-prbt-hardware-support          0.4.7-0xenial-20190320-133544-0800 amd64        Control hardware functions of the PRBT manipulator like STO for Stop1 functionality.
ii  ros-kinetic-prbt-ikfast-manipulator-plugin 0.4.7-0xenial-20190320-203437-0800 amd64        The prbt_ikfast_manipulator_plugin package
ii  ros-kinetic-prbt-moveit-config             0.4.7-0xenial-20190320-230112-0800 amd64        An automatically generated package with all the configuration and launch files for using the prbt with the MoveIt! Motion Planning Framework
ii  ros-kinetic-prbt-pg70-support              0.0.2-0xenial-20190401-162520-0800 amd64        PRBT support for Schunk pg70 gripper.
ii  ros-kinetic-prbt-support                   0.4.7-0xenial-20190320-213140-0800 amd64        Mechanical, kinematic and visual description of the Pilz light weight arm PRBT.
`

Terminal output:
`roslaunch pilz_tutorial my_application.launch
... logging to /home/pilz/.ros/log/d771aefc-7005-11e9-8f1d-f01faf1bc1f3/roslaunch-PILZNB-5709.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
unused args [rviz_config] for include of [/opt/ros/kinetic/share/prbt_moveit_config/launch/moveit_rviz.launch]
The traceback for the exception was written to the log file`

**Comment by jschleicher** [comment]
The attachment link of your launch file does not work. Can you please share your (modified) launch file?

**Comment by OndrejNedelka** [comment]
> The attachment link of your launch file does not work. Can you please share your (modified) launch file?

It should work now.
Thank you.

**Comment by martiniil** [comment]
The `rviz_config` argument is added in `prbt_moveit_config 0.4.8`. So it will be out only with the next kinetic release.
