### ISSUE TITLE
Fix unstable unittest_pilz_joint_trajectory_controller

### ISSUE THREAD

**Issue by agutenkunst** [PilzDE/pilz_robots#187]
### Commit
https://github.com/PilzDE/pilz_robots/commit/69001be9805098286fa23096b3c9d05783b20b67

This test seems to fail on travis (especially the testIsExecuting) since it heavily relies on ros::Time::now()

**Comment by martiniil** [comment]
You don't have a log by chance?
This could be related to the instability in #206, which seems to vanish or at least was heavily reduced through fd509a8d90da7f2bba1d43aa034da0267f9a788d.

**Comment by agutenkunst** [comment]
Did not occurred again so far. Will close for now. Please reopen if needed.

**Comment by agutenkunst** [comment]
Reopen ;-)
I just realized you could use sim time in this test.
See http://docs.ros.org/melodic/api/rostime/html/classros_1_1Time.html#ab569bffab97380d8a73275cdc02afb8f this would maybe even enable turning this into a unittest... 

@martiniil what do you think?

**Comment by leunMar** [comment]
I would like this very much. But I don't agree on re-opening this issue. Or did you observe that the test is still unstable? If not, I would suggest that you either change the title of this issue (and remove the bug-label) or open a new issue.

**Comment by leunMar** [comment]
Test failed again: (exceeds max time 60.0s) https://api.travis-ci.org/v3/job/601221025/log.txt

**Comment by martiniil** [comment]
Should be fixed via fcc9c2c.
