### ISSUE TITLE
Get rid of waitForService (refactoring)

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_robots#209]
Following #175 `waitForService` should be refactored into `ServiceClientFactory::create`

This would resolve the names conflict with the roscpp method: http://docs.ros.org/melodic/api/roscpp/html/namespaceros_1_1service.html

**Comment by jschleicher** [comment]
@martiniil Is this still relevant? As far as I can tell `ServiceClientFactory` class is gone again?

**Comment by martiniil** [comment]
I think you are right.
