### ISSUE TITLE
Link to "ROS-I training exercise 3.4" in README not working

### ISSUE THREAD

**Issue by SansoneG** [PilzDE/pilz_robots#215]
In the README -> under the subheading [Running the simulation](https://github.com/PilzDE/pilz_robots/blob/kinetic-devel/README.md#running-the-simulation) -> subpoint 2 -> the link to "ROS-I training exercise 3.4" is not working.

**Comment by ct2034** [comment]
Thanks for letting us know. :+1: 
The link you are looking for is now here: https://industrial-training-master.readthedocs.io/en/kinetic/_source/session3/Motion-Planning-RVIZ.html
