### ISSUE TITLE
document stop1/modbus launch files

### ISSUE THREAD

**Issue by JonathanGruner** [PilzDE/pilz_robots#228]
### Commit
Version 0.5.7

### Steps to reproduce
1. Open launch files inside `prbt_hardware_support`
2. Try to understand the parameters / arguments
3. Search comments--->There you will find the issue...no comments.
4. You won't be able to understand the code

### Expected behavior
Well documented files, especally launch files, config files, etc.

### Observed behavior
missing comments / references.

**Comment by ct2034** [comment]
@JonathanGruner Thanks for your feedback. 
Unfortunately, this is a relatively broad topic. Could you please give an example of where you think we lack documentation. _Also, feel free to open a pull request!_

**Comment by jschleicher** [comment]
This concerns e.g. launch files in the folder  

https://github.com/PilzDE/pilz_robots/blob/4d49235f22a0816058a40117aeb5f22b850d31f1/prbt_hardware_support/launch/stop1_executor_node.launch#L18-L20

Sometimes a reference to the main readme would be enough, but in this case the readme doesn't mention `stop1_executor_node` at all.

**Comment by JonathanGruner** [comment]
Another great exampel would be:
https://github.com/PilzDE/pilz_robots/blob/4d49235f22a0816058a40117aeb5f22b850d31f1/prbt_hardware_support/launch/modbus_client.launch#L29-L40

I don't want to bother you with a detailed description of each command/parameter, but if you could briefly explain what you are doing I would be happy :)

For example: num_first_register_to_read: First register adress of 4x registers type in modicon notation
num_registers: first = runpermitted, second = baketest, third = sth other

**Comment by JonathanGruner** [comment]
https://github.com/PilzDE/pilz_robots/blob/24a1c5dd8ad6be342b27bfef5a3bb13b471003ef/prbt_hardware_support/config/modbus_read_api_spec_pss4000.yaml#L1-L4

Here you could write an comment, that users are able to add different Registers

**Comment by JonathanGruner** [comment]
Closed regarding to closed issue #309 (Modbus specification) and #250 (Missing Modbus information)
