### ISSUE TITLE
Random chars at the end of firmware string

### ISSUE THREAD

**Issue by agutenkunst** [PilzDE/pilz_robots#299]
### Commit
db438915d632097fc1c29a9ebaefad27370f396b

### Steps to reproduce
Launch robot with real system

### Expected behavior
Firmware of each joint is displayed properly

### Observed behavior
Random chars are added to the firmware string

### Logfiles
```
[ INFO] [1578999408.520278926]: Firmware version [prbt_joint_1]: 100 Build:11158 Date:2018-06-07 16:49:55
[ INFO] [1578999408.520434190]: Firmware version [prbt_joint_2]: 100 Build:11158 Date:2018-06-07 16:49:55
[ INFO] [1578999408.520502982]: Firmware version [prbt_joint_3]: 100 Build:11158 Date:2018-06-07 16:49:55u
[ INFO] [1578999408.520559978]: Firmware version [prbt_joint_4]: 100 Build:11158 Date:2018-06-07 16:49:555
[ INFO] [1578999408.520618411]: Firmware version [prbt_joint_5]: 100 Build:11158 Date:2018-06-07 16:49:55E
[ INFO] [1578999408.520675839]: Firmware version [prbt_joint_6]: 100 Build:11158 Date:2018-06-07 16:49:55
```

Result of command below see [candump.log](https://github.com/PilzDE/pilz_robots/files/4058800/candump.log)
```
rosservice call /prbt/driver/get_object "node: 'prbt_joint_1'
object: '100A'
cached: false" 
success: True
message: ''
value: "100 Build:11158 Date:2018-06-07 16:49:55%"
```

**Comment by agutenkunst** [comment]
@jschleicher could you provide more objects which are strings? I would like to see if they are all off-by-one, if yes this could be an issue with https://github.com/ros-industrial/ros_canopen if not this is on us.

**Comment by jschleicher** [comment]
@agutenkunst The version registers 0x1008-0x100A are strings, see https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_support/config/prbt_0_1.dcf (grep for `DataType=0x0009`).
