### ISSUE TITLE
CAN driver needs to be manually restarted after CAN disconnect

### ISSUE THREAD

**Issue by HiddenBug** [PilzDE/pilz_robots#301]
### Observed behavior
If the connection to the robot is lost and, subsequently, established again, the CAN driver needs to be manually restarted via:
```
sudo ip link set can0 down
sudo ip link set can0 up type can bitrate 1000000
```
This statement remains true, even if the root-user changes the `/etc/network/interfaces` to automatically start the CAN driver via:
```
auto can0
iface can0 can static
        bitrate 1000000
```

**Please note:**
- The connection to the robot can be lost e.g. if the control cabinet is turned off and on again.

### Problem
The described behavior leads to some unfavorable situations:
- If the CAN driver needs to be restarted, the "normal" robot user (which is not necessarily root) suddenly needs root rights. The question is: Is this the favored behavior? Shouldn't it be our goal that the "normal" robot user does not need root rights?
- If the root user did change the  `/etc/network/interfaces` to automatically start the CAN driver: Why do we still need to manually restart the CAN driver? Why does is not happen automatically?

### Expected behavior
- The "normal" robot user should not need root rights. All "fundamental" system changes should only need to be done once by the start-up engineer and/or root of the system.
- The CAN driver should automatically restart, if the connection to the robot is lost. No further action by the user should be necessary.
- The behavior should be specified in the README.md file.

**Comment by jschleicher** [comment]
Plugging off/on the USB cable (PCANusb) should re-initialize the driver. Maybe add a note to troubleshooting section of #339?

**Comment by agutenkunst** [comment]
> Plugging off/on the USB cable (PCANusb) should re-initialize the driver. 

@tobi-v was able to confirm this on the real hardware. sudo ist not needed.
