### ISSUE TITLE
Coverage for nose tests on travis

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_robots#304]
We can currently not run pure python tests (i.e. nosetests) on travis.
I tried it here: https://github.com/PilzDE/pilz_robots/pull/285/commits/362ee70766419dcedc3f12e0b2b185b66e41f961
@agutenkunst  added instructions, how to run it locally here: https://github.com/PilzDE/pilz_robots/pull/285/commits/44fb88e0d26b9cd233d79d84767f02fbf8b9ebd6

**Comment by agutenkunst** [comment]
Solved by https://github.com/mikeferguson/code_coverage ? @ct2034

**Comment by jschleicher** [comment]
> Solved by https://github.com/mikeferguson/code_coverage ? @ct2034

No. That's just `rostest` which we currently use already. The problem of pure python tests remains.

**Comment by jschleicher** [comment]
See PilzDE/pilz_industrial_motion#282 for how to integrate coverage for python nose tests.
