### ISSUE TITLE
Travis fails for missing ros-melodic-moveit-ros-visualization

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_robots#326]
All builds on the current _testing_ deb repo are failing. 
For example: https://travis-ci.org/github/PilzDE/pilz_robots/jobs/670125275

```
E: Unable to locate package ros-melodic-moveit-ros-visualization
ERROR: the following rosdeps failed to install
  apt: command [apt-get install -y -qq ros-melodic-moveit-ros-visualization] failed
```

**Comment by ct2034** [comment]
The error happened on the buildfarm, too. But seems to be fixed there now. http://build.ros.org/job/Kdev__pilz_robots__ubuntu_xenial_amd64/

**Comment by martiniil** [comment]
http://repositories.ros.org/status_page/ros_melodic_default.html?q=moveit_ros_visualization

https://github.com/ros-planning/moveit/issues/1996

**Comment by martiniil** [comment]
Fixed: https://travis-ci.org/github/PilzDE/pilz_robots/builds/672431148
