### ISSUE TITLE
Allow robot.launch without modbus

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/pilz_robots#329]
### Commit
44a3d6b

### Steps to reproduce
1. create your own application package as in https://github.com/PilzDE/pilz_application_templates/
2. try to startup without modbus connection

### Expected behavior
bringup should be possible without modbus (at least for debugging whether a communication problem lies in can or modbus connection)

### Observed behavior
Startup always includes modbus.

From https://github.com/PilzDE/pilz_application_templates Readme:
It should not be necessary, to change the original launch files robot.launch or move_group.launch and thus fork pilz_robots. If there are any options missing, please file an Issue.

### Reference to test
Braketest and status_indicator can be disabled individually, but the modbus node is always present.

**Comment by martiniil** [comment]
This sounds more like a missing feature. I think we can combine this with #327.

**Comment by hslusarek** [comment]
@dbakovic is going to write a story for this issue. Therefore, I more or less consider this issue closed.

**Comment by martiniil** [comment]
@jschleicher 
- Should the user be able to command robot movements in general?
- Should the user be able to command the robot via the Python API?

**Comment by jschleicher** [comment]
Solved with #353
