### ISSUE TITLE
ROSException: timeout exceeded while waiting for service /prbt/get_speed_override

### ISSUE THREAD

**Issue by tswie** [PilzDE/pilz_robots#337]
- [ ] test

### Commit
Latest melodic push.

### Steps to reproduce
This happens when I attempt to run a motion server for my robot using PILZ. 

### Expected behavior
The server should launch and await requests from other programs.

### Observed behavior
The initialization times out waiting for the /prbt/get_speed_override service. This code previously worked on kinetic. 

Which node is supposed to run this service exactly? I can't find it anywhere.

**Comment by hslusarek** [comment]
Hello,
first off, thanks for your report. In order, to understand your problem I need more information.

Firstly, what do you mean by "latest melodic push"? Do you mean commit ce7cb7f5c6e23057b7a9dd6611e725a0d090d0d3 from [pilz_robot](https://github.com/PilzDE/pilz_robots)?

The service `/prbt/get_speed_override service` is provided by the `OperationModeSetupExecutor` see [operation_mode_setup_executor_node.cpp line 80](https://github.com/PilzDE/pilz_robots/blob/ce7cb7f5c6e23057b7a9dd6611e725a0d090d0d3/prbt_hardware_support/src/operation_mode_setup_executor_node.cpp#L80) and [operation_mode_setup_executor.cpp line 65](https://github.com/PilzDE/pilz_robots/blob/ce7cb7f5c6e23057b7a9dd6611e725a0d090d0d3/prbt_hardware_support/src/operation_mode_setup_executor.cpp#L65).

The note is started via [`moveit_planning_execution.launch`](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_moveit_config/launch/moveit_planning_execution.launch#L73) -> [`robot.launch`](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_support/launch/robot.launch#L87) -> [`operation_mode.launch`](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/launch/operation_mode.launch#L21) -> [`operation_mode_setup_executor_node.launch`](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/launch/operation_mode_setup_executor_node.launch)

  


> [...] when I attempt to run a motion server for my robot using PILZ.

Can you provide more information regarding this statement, please?

**Comment by hslusarek** [comment]
The `/prbt/get_speed_override` service also exists in `kinetic-devel` see [operation_mode_setup_executor_node.cpp](https://github.com/PilzDE/pilz_robots/blob/73d2dc0aa4ce163025bfa24710f51d6063f55338/prbt_hardware_support/src/operation_mode_setup_executor_node.cpp#L80) on `kinetic-devel`.

**Comment by jschleicher** [comment]
@tswie The service is provided by the modbus communcation nodes when running a real PRBT hardware setup including safety controller. Without operationmode feature just launch `fake_speed_override_node` as in https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/launch/fake_safety_interface.launch.
