### ISSUE TITLE
Write Tutorial on how-to setup robot

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_robots#339]
Create a tutorial which explains:
- [x] how to connect the cables to the robot,
- [x] launch a simple bring-up application.
- [ ] troubleshooting
- [x] terminate can
- [x] can baudrate

http://wiki.ros.org/pilz_robots/Tutorials/HowToSetupTheRobot

**Comment by hslusarek** [comment]
Created empty tutorial page: [pilz_robots/Tutorials/HowToSetupTheRobot](https://wiki.ros.org/pilz_robots/Tutorials/HowToSetupTheRobot)

**Comment by martiniil** [comment]
Files for the tutorial: https://github.com/PilzDE/pilz_tutorials/pull/12/files

**Comment by SansoneG** [comment]
Consider using [GetTaggedCode](http://library.isr.ist.utl.pt/docs/roswiki/WikiMacros.html#GetCode.2C_GetTaggedCode) to keep the tutorials synced with github repo.
Same for https://github.com/PilzDE/pilz_tutorials/pull/12#issue-408381844

**Comment by SansoneG** [comment]
[Model your first application using the Pilz Manipulator Module PRBT](https://wiki.ros.org/pilz_robots/Tutorials/ModelYourApplicationWithPRBT) -> This is listed as `Next Tutorial` and under `Prerequisites`

**Comment by agutenkunst** [comment]
> [Model your first application using the Pilz Manipulator Module PRBT](https://wiki.ros.org/pilz_robots/Tutorials/ModelYourApplicationWithPRBT) -> This is listed as `Next Tutorial` and under `Prerequisites`

If fixed this.
