### ISSUE TITLE
Modbus disconnected when Basler camera is taking a picture

### ISSUE THREAD

**Issue by CloudYin** [PilzDE/pilz_robots#358]
### Steps to reproduce
How can the issue/bug be reproduced?
1. Launch the robot, execute a move script.
2. After the robot moves to a defined pose. Take a picture by Basler camera, using standard script by Basler.
[https://github.com/basler/pypylon/blob/master/samples/save_image.py](url)
3. Error occurred. Modbus disconnected.

### Expected behavior
Camera take a picture when the robot is at the defined pose. 

### Observed behavior
Modbus connection lost.

### Logfiles
[ERROR] [1587704111.669731267]: Failed to read 4 registers starting from 512 with err: Connection timed out
[ERROR] [1587704111.670045348]: Modbus disconnect: Failed to read 4 registers starting from 512 with err: Connection timed out
[ERROR] [1587704111.671363528]: A disconnect from the modbus server happend.

**Comment by jschleicher** [comment]
solved using a second ethernet interface. Separating modbus from other traffic.
