### ISSUE TITLE
Plan when and if the repos are released

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_robots#359]

**Comment by agutenkunst** [comment]
After consulting with the team this issue needs a melodic release today.

**Comment by jschleicher** [comment]
Please also update https://github.com/PilzDE/pilz_application_templates/blob/4b0cd240aac62ac7a94ff0d8c2418c319ca14bdf/prbt_default_application/CHANGELOG.rst with the new pilz_robots version and date of release. Thanks!

**Comment by agutenkunst** [comment]
https://github.com/ros/rosdistro/pull/24700
