### ISSUE TITLE
Execute Acceptance tests at real robot

### ISSUE THREAD

**Issue by SansoneG** [PilzDE/pilz_robots#366]
Have a look at `pilz_robots` and `pilz_industrial_motion` for Acceptance Tests.

**Comment by SansoneG** [comment]
The following was noticed while executing braketests at the real robot:
- testing limit for joint 5 doesn't make sense
- the folder names for acceptance tests isn't consistent (e.g. `prbt_support `and `prbt_hardware_support`)
- test could be made more efficient
- Wrong value is written to modbus in https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/src/modbus_adapter_brake_test.cpp#L138
- In https://github.com/PilzDE/pilz_robots/blob/bf93b848fe1646b5480f7c2b4afa88fa4c7f7d4b/prbt_support/test/acceptance_tests/acceptance_test_joint_limits.md the pressing of enabling switch while startup is not mentioned

**Comment by martiniil** [comment]
We detected a problem: #379
