### ISSUE TITLE
Check for known errors

### ISSUE THREAD

**Issue by SansoneG** [PilzDE/pilz_robots#367]
**Known errors:**
- [x] Quickly press and release the enabling switch repeatedly
- [x] Start system with and without enabling switch pressed

**-**
- [x] Write Acceptance Tests for known errors

**Additonal Info:**
See #93

**Comment by martiniil** [comment]
In order to check if the EMCY reported in #93 would still appear, we could check out the last commit before the fix: fe648ea84569858d58ea9e4c40296f3409609412.

It is not relevant for us now, but it would confirm that it is fixed in the firmware.

**Comment by martiniil** [comment]
Created new PR #378
