### ISSUE TITLE
Automate an existing acceptance test with test cell and new firmware

### ISSUE THREAD

**Issue by SansoneG** [PilzDE/pilz_robots#370]
- [ ] Choose an acceptance test from https://github.com/PilzDE/pilz_industrial_motion/tree/melodic-devel/pilz_robot_programming/test/acceptance_tests
- [ ] Automate it like example found at https://github.com/PilzDE/pilz_testutils/tree/melodic-devel/pilz_robot_tfc_api/examples
- [ ] Implement measurement API e.g. allowing the tests to evaluate the motion of the robot during test
- [ ] Write how-to guide for test facility

**Note:** 
Please see PR:
https://github.com/PilzDE/pilz_industrial_motion/pull/269

**Comment by hslusarek** [comment]
Please see PR #269

**Comment by jschleicher** [comment]
Since the current PBI is mostly about enabling and stopping, maybe https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/test/acceptancetests/acceptancetest_stop1.md would be a good first candidate for automation?

**Comment by martiniil** [comment]
Delayed until test cell is ready.
