### ISSUE TITLE
Link Tutorial modbus on overview page 

### ISSUE THREAD

**Issue by SansoneG** [PilzDE/pilz_robots#374]
http://wiki.ros.org/pilz_robots/Tutorials

**Comment by jschleicher** [comment]
As a tutorial series, adding it from the [first tutorial](http://wiki.ros.org/pilz_robots/Tutorials/HowToSetupTheRobot) as "next" should also add it to the overview page.

**Comment by SansoneG** [comment]
That is correct. I'm wondering though, whether a tutorial series is the appropriate tool to use in this case, since there is no logical progression between the CAN tutorial and the Modbus tutorial.
A user should be able to execute them chronologically independent from each other,

**Comment by hslusarek** [comment]
Story delayed -> Close.
