### ISSUE TITLE
Review acceptance test (READY)

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_robots#400]
See #308 commit 49d3e03.

**Comment by agutenkunst** [comment]
I checked 
https://github.com/PilzDE/pilz_robots/blob/49d3e03b191f84367f583cf9f9e0505e020b5cef/pilz_control/test/acceptance_test_speed_monitoring.md

https://github.com/PilzDE/pilz_robots/blob/49d3e03b191f84367f583cf9f9e0505e020b5cef/pilz_control/test/acceptance_test_speed_monitoring.py
and had some remarks.

See https://github.com/PilzDE/pilz_robots/pull/308#pullrequestreview-419066442

**Comment by agutenkunst** [comment]
Reassign on @martiniil

**Comment by martiniil** [comment]
@agutenkunst Why did you skip the other files? `joint_states_speed_observer.*`?

**Comment by agutenkunst** [comment]
> @agutenkunst Why did you skip the other files? `joint_states_speed_observer.*`?

Sry missed. Now added comments.

See especially https://github.com/PilzDE/pilz_robots/commit/49d3e03b191f84367f583cf9f9e0505e020b5cef#r39482161

but also the other comments....
