### ISSUE TITLE
Error Code is not shown when executing braketest from terminal

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_robots#402]
Commit d31686c0434a5848105121e8a155a8ad16d77989

In [acceptancetest_execute_brake_test.md](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/prbt_hardware_support/test/acceptance_tests/acceptancetest_execute_brake_test.md) we assumed that the error codes would be printed on the console when running `rosservice call /prbt/execute_braketest`. But this is not the case.

**Comment by jschleicher** [comment]
Fixed in #403
