### ISSUE TITLE
PNOZ safety hardware uses wrong registers + missing modbus_write_api_pnoz.yaml

### ISSUE THREAD

**Issue by JonathanGruner** [PilzDE/pilz_robots#444]
### Commit
Current one

### Steps to reproduce
How can the issue/bug be reproduced?
1. Connect PNOZ
2. Download pilz_application_template
2. Change safety_hw parameter to "pnoz"

### Expected behavior
- Uses registers 512...515
- No further changes necessary

### Observed behavior
- Uses PSS4000 registers 970...980
- You have to make an empty file modbus_write_api_pnoz.yaml in the config folder because of errors when your program tries to read an non existend file

### Workaround
- Replace the modbus_<read/write>_client_pss4000.yaml with pnoz files to match with pnoz registers

- $ sudo touch /opt/ros/melodic/share/prbt_hardware_support/config/modbus_write_api_spec_pnoz.yaml

- $ sudo mv /opt/ros/melodic/share/prbt_hardware_support/config/modbus_write_api_spec_pnoz.yaml /opt/ros/melodic/share/prbt_hardware_support/config/modbus_write_api_spec_pss4000.yaml

- $ sudo mv /opt/ros/melodic/share/prbt_hardware_support/config/modbus_read_api_spec_pnoz.yaml /opt/ros/melodic/share/prbt_hardware_support/config/modbus_read_api_spec_pss4000.yaml

**Comment by martiniil** [comment]
Thank you for reporting the issue.
The error with the missing file should disappear once you set `has_braketest_support:=false`. At least this is the intended setup for Pnoz.

**Comment by martiniil** [comment]
@jschleicher The issue occurs because the filename of the config file is not passed to `modbus_client.launch`. This is already fixed here: #384

**Comment by JonathanGruner** [comment]
> 
> 
> Thank you for reporting the issue.
> The error with the missing file should disappear once you set `has_braketest_support:=false`. At least this is the intended setup for Pnoz.

Thanks for the answer. I checked but the parameter is set to "false", therefore this can't be the reason. If you want I can send you my package.

**Comment by martiniil** [comment]
> > Thank you for reporting the issue.
> > The error with the missing file should disappear once you set `has_braketest_support:=false`. At least this is the intended setup for Pnoz.
> 
> Thanks for the answer. I checked but the parameter is set to "false", therefore this can't be the reason. If you want I can send you my package.

Thanks Jonathan. Please post a log of the error. Let's see if this helps.

**Comment by JonathanGruner** [comment]
[roslaunch-rospc-HP-ProBook-650-G5-10296.log](https://github.com/PilzDE/pilz_robots/files/4987227/roslaunch-rospc-HP-ProBook-650-G5-10296.log)


[my_application.launch.txt](https://github.com/PilzDE/pilz_robots/files/4987229/my_application.launch.txt)

**Comment by martiniil** [comment]
Your log shows that the file `modbus_read_api_spec_pnoz.yaml` is missing. I guess this is due to your workaround, in which this file is renamed. Can you revert your workaround (completely!) and post the log of the original error?

**Comment by JonathanGruner** [comment]
Ok you are right. Got confused with the errors and reseted the whole config folder into original. Than the error is gone.

**Comment by martiniil** [comment]
Hi @JonathanGruner , this issue should be fixed right now on the branch `melodic-devel`. It would be nice if you could validate it.

**Comment by JonathanGruner** [comment]
Hi,
it works with this branch melodic-devel. 
Tested it with prbt_default_application.
I will disassemble my testing cell now and close this request, thank you very much for your effort!
