### ISSUE TITLE
/etc/network/interfaces does not exist on ubuntu 20.04

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_robots#485]
We need to fix this here and in the tutorials

**Comment by CloudYin** [comment]
> We need to fix this here and in the tutorials

This can be done by enabling systemd-networkd. Here is the procedure:
1. In the terminal, run the following two commands:
sudo systemctl start systemd-networkd
sudo systemctl enable systemd-networkd
2. Configure SocketCan network interface in systemd-networkd:
sudo nano /etc/systemd/network/80-can.network
3. In the open file, add the following text:
[Match]
Name=can*
[CAN]
BitRate=1000000

4. Restart systemd-networkd by the command:
sudo systemctl restart systemd-networkd
