### ISSUE TITLE
PluginlibFactory: The plugin for class 'moveit_rviz_plugin/MotionPlanning' failed to load.

### ISSUE THREAD

**Issue by SantiagoCanete** [PilzDE/pilz_robots#488]
### Commit
Installed the library through 
`sudo apt install ros-noetic-pilz-robots`

### Setup
Using Ubuntu 20.04, ROS Noetic in WSL

### Tried
1. `sudo apt update`
2. `sudo apt-get dist-upgrade`
3. `sudo apt-get install ros-noetic-moveit-visual-tools`

### Expected behavior
Running the test launch:
`roslaunch prbt_moveit_config moveit_planning_execution.launch`

### Observed behavior
`[ERROR] PluginlibFactory: The plugin for class 'moveit_rviz_plugin/MotionPlanning' failed to load.  Error: Failed to load library /opt/ros/noetic/lib/libmoveit_motion_planning_rviz_plugin.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libfcl.so.0.6: cannot open shared object file: No such file or directory)`

**Comment by martiniil** [comment]
I assume you installed `ros-noetic-pilz-robots`?

**Comment by martiniil** [comment]
I tried it in a fresh container (docker) and could not observe an issue. Regarding WSL, I cannot help unfortunately.

**Comment by SantiagoCanete** [comment]
Yeap, sorry I installed `ros-noetic-pilz-robots`. I edited the original issue. This seems to be related to WSL, unsetting the environment variable `export LIBGL_ALWAYS_INDIRECT=:` in .bashrc has solved the problem.
