### ISSUE TITLE
Gazebo integrationtest errors

### ISSUE THREAD

**Issue by martiniil** [PilzDE/pilz_robots#70]
### Commit
93454eb1c7e1fe3e46ec47d8d778d73d68722161

### Steps to reproduce
This happened here: https://travis-ci.org/PilzDE/pilz_robots/jobs/492676506
I do not know, how to reproduce it.

### Log

> [ INFO] [1550063952.451245135]: Loading robot model 'prbt'...
[ WARN] [1550063952.451764145]: Skipping virtual joint 'FixedBase' because its child frame 'prbt_base_link' does not match the URDF frame 'world'
[ INFO] [1550063952.452015314]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ INFO] [1550063953.094379308]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1550063953.107568358]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1550063953.189882115]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1550063953.231851913]: MoveGroup debug mode is OFF
Starting context monitors...
[ INFO] [1550063953.231918243]: Starting scene monitor
[ INFO] [1550063953.278778984]: Listening to '/planning_scene'
[ INFO] [1550063953.278831298]: Starting world geometry monitor
[ INFO] [1550063953.325316757]: Listening to '/collision_object' using message notifier with target frame '/world '
[ INFO] [1550063953.331388117]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1550063953.345524752]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ INFO] [1550063953.391006143]: Initializing OMPL interface using ROS parameters
SpawnModel script started
[ INFO] [1550063953.452645766]: Using planning interface 'OMPL'
[ INFO] [1550063953.471948682]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1550063953.473790777]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1550063953.475083585]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1550063953.476805438]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1550063953.478555325]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1550063953.480034626]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1550063953.480121613]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1550063953.480146465]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1550063953.480170137]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1550063953.480196078]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1550063953.480210983]: Using planning request adapter 'Fix Start State Path Constraints'
[INFO] [1550063953.545793, 0.000000]: Loading model XML from ros parameter
[INFO] [1550063953.548924, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
Error [parser.cc:581] Unable to find uri[model://sun]
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
You can start planning now!
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 313, in <module>
    sm.callSpawnService()
  File "/opt/ros/kinetic/lib/gazebo_ros/spawn_model", line 271, in callSpawnService
    initial_pose, self.reference_frame, self.gazebo_namespace)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/gazebo_ros/gazebo_interface.py", line 28, in spawn_urdf_model_client
    rospy.wait_for_service(gazebo_namespace+'/spawn_urdf_model')
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 159, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown
[WARN] [1550064013.559037, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[Testcase: testintegrationtest_gazebo_bringup] ... ERROR!
ERROR: max time [60.0s] allotted for test [integrationtest_gazebo_bringup] of type [prbt_gazebo/integrationtest_gazebo_bringup]

**Comment by agutenkunst** [comment]
`Error [parser.cc:581] Unable to find uri[model://sun]`
Is something I experienced before and the reason why this happens is unclear to me.
