### ISSUE TITLE
rosparam can

### ISSUE THREAD

**Issue by JonathanGruner** [PilzDE/pilz_robots#72]
Please insert the hint, that you could change with the param

`<rosparam param="/prbt/driver/bus/device">canx</rosparam>`

with x the number of Can in the moveit_planning_execution.launch.

**Comment by agutenkunst** [comment]
Is https://github.com/PilzDE/pilz_robots/blob/3e8b31ea3ebceb120be15aec609a5ae6af55db76/prbt_support/launch/robot.launch#L15-L17

sufficient?

**Comment by jschleicher** [comment]
Yep. This issue is about **documentation**.

Maybe the future tutorial about connecting the real robot would be a good place. Maybe we should put this into an example package together with ready-to-use-script(s). I think this should be visible somewhere on wiki.ros.org. What do you think?
