### ISSUE TITLE
A3 joint limit violation in transport position 

### ISSUE THREAD

**Issue by CloudYin** [PilzDE/pilz_robots#82]
Hi gentlemen,

when I set the robot to the transport position it always shows a joint violation error. I made a test for each axis and find the axis A3 cannot set to -135 degree. However -134 is ok. Here is the code I write:

https://github.com/yzhyff/prbt_training_cell/blob/1fccbda495a618bdb712919f4f61d94ff2c2f297/prbt_training_cell/scripts/transport.py#L1

**Comment by martiniil** [comment]
@CloudYin Thank you for reporting this issue. We will tackle it in the next days.
