### ISSUE TITLE
Re-generate ikfast plugin

### ISSUE THREAD

**Issue by jschleicher** [PilzDE/pilz_robots#83]
### Commit
3efae68

### Steps to reproduce
How can the issue/bug be reproduced?
1. `roslaunch prbt_moveit_config moveit_planning_execution.launch`

### Expected behavior
No warnings appear.

### Observed behavior
Log output:
```
[ WARN] [1552987873.840199096]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/rviz_ROS_PC_6811_9210959308488888664/manipulator/kinematics_solver_attempts' from your configuration.
[ WARN] [1552987873.848169752]: IK plugin for group 'manipulator' relies on deprecated API. Please implement initialize(RobotModel, ...).
```

### Reference to test
Maybe a test checking for warning in /rosout during normal launch would help?

The fix should be as easy as re-generating the plugin from the current moveit master (see [moveit commit f19e411](https://github.com/ros-planning/moveit/commit/f19e411f2c4464783fd3994e6d3f6600adca7c91#diff-c0919d8a62d0d141b12acc2bf76ba7ed)

Related to #44  (hotfix)

**Comment by ct2034** [comment]
This is currently only relevant in melodic
