### ISSUE TITLE
When modbus fails to read register, it outputs "Modbus disconnected!"

### ISSUE THREAD

**Issue by ct2034** [PilzDE/pilz_robots#89]
### Commit
f8064345f37a2dcaaf26b4130ab71c5df331ae7a

### Steps to reproduce
Have a hardware setup failing to read modbus register

### Expected behavior
Log output should describe failure accurately:
````
Failed to read modbus registers!
````

### Observed behavior
Log output is:
````
Modbus disconnected!
````

**Comment by jschleicher** [comment]
Closed by #91
