### ISSUE TITLE
CAN Error SAFE_TORQUE_OFF (ER: 129)

### ISSUE THREAD

**Issue by JonathanGruner** [PilzDE/pilz_robots#93]
### Commit
Ubuntu 18.04 using ROS melodic.

### Steps to reproduce
How can the issue/bug be reproduced?
1. Start the robot with holding the Enabling switch
2. Release the switch, press it again, release it, ..... 
3. The Error will occur and the brakes won't open again after a few (sometimes even after the first) releases of the switch
4. If I don't release the button (or in my case close and lock the door of the cell in automatic mode) the error won't occur as often as with the other tactic.

### Expected behavior
I expected, that the robot will continue working after the enabling switch is pressed again.

### Observed behavior
After Error I have to reboot the program (not the robot) to make it work again

### Logfiles
CAN Log:
[candump-2019-03-27_105509.log](https://github.com/PilzDE/pilz_robots/files/3012949/candump-2019-03-27_105509.log)

Console Log:
[Terminal output.txt](https://github.com/PilzDE/pilz_robots/files/3012956/Terminal.output.txt)

**Comment by jschleicher** [comment]
The emergency `EMCY: 87#001081 29 03000000` is         `ERROR_SAFE_TORQUE_OFF  //0x29`

**Comment by ct2034** [comment]
This was **not** reproducible with firmware
```
"100 Build:11158 Date:2018-06-07 16:49:55%"
```

**Comment by JonathanGruner** [comment]
I have firmware:
``` "101 Build 11345 Date:2018-12-17 07:33:065" ```
Its different!

**Comment by ct2034** [comment]
In the archive there are three can logs for comparison:
[can_dumps_wireshark.zip](https://github.com/PilzDE/pilz_robots/files/3191531/can_dumps_wireshark.zip)
- `fw100_error129_no_failure_gz.pcapng`: old firmware - error does not appear
- `fw101_error129_failes_gz.pcapng`: new firmware - fails
- `fw101_error129_workaround_gz.pcapng`: with workaround

**Comment by martiniil** [comment]
Closed via #175
